version: '3.5'

services:

    app:
        build: .
        container_name: "${PROJECT_NAME}_app"
        volumes:
            - .:/var/www
            - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - catalog
        depends_on:
            - db
            - redis
        environment:
            - OPCACHE_ENABLE=${OPCACHE_ENABLE:-1}
            - XDEBUG_MODE=${XDEBUG_MODE:-debug}
            - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST:-host.docker.internal}
            - XDEBUG_CLIENT_PORT=${XDEBUG_CLIENT_PORT:-9003}

    nginx:
        build: .docker/nginx
        container_name: "${PROJECT_NAME}_nginx"
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - catalog
        depends_on:
            - app

    db:
        build: ./.docker/mysql
        container_name: "${PROJECT_NAME}_db"
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=code_micro_videos
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - catalog

    redis:
        image: redis:alpine
        container_name: "${PROJECT_NAME}_redis"
        networks:
            - catalog

networks:
    catalog:
     driver: bridge
